# Dockerfile that installs and compiles the dependencies for OAI (e.g. uhd, asn1c etc).
# After building this image, you can use Dockerfile.build to compile the OAI executables.
# For the original Dockerfiles, see the official OpenAirInterface (OAI) repository at
#   https://gitlab.eurecom.fr/oai/openairinterface5g/


FROM ubuntu:noble AS oai-deps

ENV DEBIAN_FRONTEND=noninteractive
ENV TZ=Europe/Paris
ENV BUILD_UHD_FROM_SOURCE=True
ENV UHD_VERSION=4.8.0.0

# Install build packages
RUN apt-get update && \
    apt-get upgrade --yes && \
    apt-get install --yes build-essential ccache psmisc git xxd libpcre2-dev python3-dev bison flex m4 python3-pip wget && \
    # --break-system-packages allows externally managed environment in pip 
    pip3 install --ignore-installed pyyaml --break-system-packages;

# Copy the files needed to install and build the dependencies
WORKDIR /oai-ran/cmake_targets/tools
COPY cmake_targets/tools/build_helper \
     cmake_targets/tools/uhd-4.x-tdd-patch.diff \
     ./

WORKDIR /oai-ran/cmake_targets
COPY cmake_targets/build_oai .

WORKDIR /oai-ran
COPY oaienv .

# Install and build the dependencies
RUN /bin/sh oaienv && \ 
    cd cmake_targets && \
    mkdir -p log && \
    ./build_oai -I -w USRP --install-optional-packages
