# Single Dockerfile that compiles NR UE and gNB into a single image.
# For development, use Dockerfile.deps, Dockerfile.build, Dockerfile.nrUE, and Dockerfile.gNB
#   to avoid installing and building dependencies every time.
# For the original Dockerfiles, see the official OpenAirInterface (OAI) repository at
#   https://gitlab.eurecom.fr/oai/openairinterface5g/


FROM ubuntu:noble AS builder
ARG BUILD_OPTION

ENV DEBIAN_FRONTEND=noninteractive
ENV TZ=Europe/Paris
ENV BUILD_UHD_FROM_SOURCE=True
ENV UHD_VERSION=4.8.0.0

# Install build packages
RUN apt-get update && \
    apt-get upgrade --yes && \
    apt-get install --yes build-essential ccache psmisc git xxd libpcre2-dev python3-dev bison flex m4 python3-pip wget && \
    # --break-system-packages allows externally managed environment in pip 
    pip3 install --ignore-installed pyyaml --break-system-packages;

# Copy the OAI source code
WORKDIR /oai-ran
COPY . .

# First install and build the dependencies
# Then build the OAI executables (NR UE and gNB)
# NOTE: Keep the first line that calls the ./build_oai script, so that UHD can be properly installed
RUN \
   # Mount CCache cache directory
   --mount=type=cache,target=/root/.cache/ccache/ \
   # Mount CPM package cache
   --mount=type=cache,target=/root/.cache/cpm/ \
    /bin/sh oaienv && \
    cd cmake_targets && \
    mkdir -p log && \
    ./build_oai -I -w USRP --install-optional-packages && \
    ./build_oai -c --ninja \
      --nrUE --gNB \
      -w USRP -t Ethernet \
      --noavx512 \
      --build-tool-opt -k10 \
      --cmake-opt -DCMAKE_C_FLAGS="-Werror" --cmake-opt -DCMAKE_CXX_FLAGS="-Werror" "$BUILD_OPTION" && \
    # Mainly to see if the sanitize option was perfectly executed
    echo "---- ldd on executables ----" && \
    ldd ran_build/build/*softmodem* ran_build/build/nr-cuup && \
    echo "---- ldd on shared libraries ----" && \
    ldd ran_build/build/*.so;


# Start from scratch for the target OAI executables (NR UE and gNB)
FROM ubuntu:noble AS oai-all

ARG BUILD_OPTION

# Install runtime packages
RUN apt-get update && \
    apt-get upgrade --yes && \
    apt-get install --yes software-properties-common procps libsctp1 libboost-chrono1.83.0 libboost-date-time1.83.0 libboost-filesystem1.83.0 \
        libboost-regex1.83.0 libboost-serialization1.83.0 libboost-thread1.83.0 libboost-system1.83.0 libboost-program-options1.83.0 \
        tzdata liblapacke libblas3 libconfig9 openssl net-tools iperf iperf3 iproute2 iputils-ping gdb python3 python3-six python3-requests \
        libusb-1.0-0 libyaml-cpp-dev vim less && \
# If the --sanitize option was used to build, additional packages are required
    /bin/bash -c 'if [[ "$BUILD_OPTION" = "--sanitize" ]]; then DEBIAN_FRONTEND=noninteractive apt-get install --yes \
        libasan8 \
        libubsan1; fi' && \
    apt-get clean -y && \
    rm -rf /var/lib/apt/lists/*;

# Copy the target executables (NR UE and gNB)
WORKDIR /opt/oai-nr/bin
COPY --from=builder /oai-ran/cmake_targets/ran_build/build/nr-uesoftmodem ./
COPY --from=builder /oai-ran/cmake_targets/ran_build/build/nr-softmodem ./

# Copy configuration files for NR UE and gNB
# (Not needed for NR UE if it is started with the command-line parameters and the default values for the rest)
WORKDIR /opt/oai-nr/etc
COPY ./targets/PROJECTS/GENERIC-NR-5GC/CONF/ue.conf ./
COPY ./targets/PROJECTS/GENERIC-NR-5GC/CONF/ue.nr.prs.fr1.106prb.conf ./
COPY ./targets/PROJECTS/GENERIC-NR-5GC/CONF/gnb.sa.band78.fr1.106PRB.usrpb210.conf ./
COPY ./targets/PROJECTS/GENERIC-NR-5GC/CONF/gnb-du.sa.band78.106prb.rfsim.pci0.conf ./
COPY ./targets/PROJECTS/GENERIC-NR-5GC/CONF/gnb-cu.sa.f1.conf ./

# Copy dynamic libraries
COPY --from=builder \
    /oai-ran/cmake_targets/ran_build/build/liboai_eth_transpro.so \
    /oai-ran/cmake_targets/ran_build/build/librfsimulator.so \
    /oai-ran/cmake_targets/ran_build/build/liboai_usrpdevif.so \
    /oai-ran/cmake_targets/ran_build/build/libcoding.so \
    /oai-ran/cmake_targets/ran_build/build/libparams_libconfig.so \
    /oai-ran/cmake_targets/ran_build/build/libdfts.so \
    /oai-ran/cmake_targets/ran_build/build/libldpc*.so \
    /oai-ran/cmake_targets/ran_build/build/libparams_yaml.so \
    /oai-ran/cmake_targets/ran_build/build/libvrtsim.so \
    /usr/local/lib/

# Copy UHD files
COPY --from=builder /usr/local/bin/uhd_find_devices /usr/local/bin
COPY --from=builder /usr/local/lib/libuhd.so.4.8.0 /usr/local/lib
COPY --from=builder /usr/local/lib/uhd/utils/uhd_images_downloader.py /opt/oai-nr/bin

RUN /bin/bash -c "ln -s /usr/local/lib/liboai_usrpdevif.so /usr/local/lib/liboai_device.so" && \
    ldconfig && \
    echo "---- ldd on nr-uesoftmodem ----" && \
    ldd /opt/oai-nr/bin/nr-uesoftmodem && \
    echo "---- ldd on nr-softmodem ----" && \
    ldd /opt/oai-nr/bin/nr-softmodem && \
    echo "---- ldd on shared libraries ----" && \
    ldd /usr/local/lib/liboai_eth_transpro.so \
        /usr/local/lib/librfsimulator.so \
        /usr/local/lib/liboai_usrpdevif.so \
        /usr/local/lib/libcoding.so \
        /usr/local/lib/libparams_libconfig.so \
        /usr/local/lib/libdfts.so \
        /usr/local/lib/libldpc*.so \
        /usr/local/lib/libuhd.so.4.8.0

WORKDIR /opt/oai-nr
#EXPOSE 2152/udp  # S1U, GTP/UDP
#EXPOSE 22100/tcp # ?
#EXPOSE 36412/udp # S1C, SCTP/UDP
#EXPOSE 36422/udp # X2C, SCTP/UDP
#EXPOSE 50000/udp # IF5 / ORI (control)
#EXPOSE 50001/udp # IF5 / ECPRI (data)

CMD ["/bin/bash"]
